apiVersion: v1
kind: Config
clusters:
  - name: authn
    cluster:
      certificate-authority: /root/cdk/ca.crt
      server: https://127.0.0.1:{{ port }}/{{ api_ver }}
users:
  - name: kube-apiserver
contexts:
- context:
    cluster: authn
    user: kube-apiserver
  name: authn
current-context: authn
