#!/usr/local/sbin/charm-env python3
import os
import json
from charmhelpers.core.hookenv import (
    action_get,
    action_set,
    action_fail,
    action_name
)
from charmhelpers.core.templating import render
from subprocess import check_output


def _kubectl(args):
    """
    Executes kubectl with args as arguments
    """
    snap_bin = os.path.join(os.sep, "snap", "bin")
    env = os.environ.copy()
    env["PATH"] = os.pathsep.join([snap_bin, env["PATH"]])
    cmd = ["kubectl", "--kubeconfig=/home/ubuntu/config"]
    cmd.extend(args)
    return check_output(cmd, env=env)


def get_kubeconfig():
    """
    Read the kubeconfig on the master and return it as JSON
    """
    try:
        result = _kubectl(["config", "view", "-o", "json", "--raw"])
        # JSON format verification
        kubeconfig = json.dumps(json.loads(result))
        action_set({"kubeconfig": kubeconfig})
    except JSONDecodeError as e:
        action_fail("Failed to parse kubeconfig: {}".format(str(e)))
    except Exception as e:
        action_fail("Failed to retrieve kubeconfig: {}".format(str(e)))

action = action_name()
if action == "get-kubeconfig":
    get_kubeconfig()
