#!/bin/sh
set -eux

if [[ "$(action-get fix-cluster-name)" == "true" ]]; then
    charms.reactive set_state kubernetes-master.cluster-name.new
    charms.reactive remove_state kubernetes-master.cluster-name.legacy
fi

charms.reactive set_state kubernetes-master.upgrade-specified
exec hooks/config-changed
