{
 "title": "K8s Deployments",
 "description": "Deployment overview for Kubernetes deploys.",
 "tags": [
  "kubernetes",
  "Juju"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "cluster", "query": "grafana-kubernetes-datasource" },
   { "name": "ds", "query": "datasource" },
   { "name": "datasource", "query": "prometheus" },
   { "name": "node", "query": "node" },
   { "name": "namespace", "query": "namespace" },
   { "name": "deployment", "query": "deployment $namespace" }
  ]
 },
 "panels": [
  {
   "title": "Deployment Replicas - Desired",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas{deployment=~\"$deployment\"})"
    }
   ]
  },
  {
   "title": "Deployments Replicas - Available",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_available{deployment=~\"$deployment\"})"
    }
   ]
  },
  {
   "title": "Deployments Replicas - Up-to-date",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_updated{deployment=~\"$deployment\"})"
    }
   ]
  },
  {
   "title": "Deployments Replicas - Unavailable",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_unavailable{deployment=~\"$deployment\"})"
    }
   ]
  },
  {
   "title": "Generations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_deployment_status_observed_generation",
     "legendFormat": "{{ deployment }}"
    }
   ]
  }
 ]
}