{
 "title": "Charmed Kubernetes Dashboard",
 "description": "Monitors Kubernetes cluster using Prometheus. Shows overall cluster CPU / Memory / Filesystem usage as well as individual pod, containers, systemd services statistics.",
 "tags": [
  "Juju",
  "Kubernetes"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": "label_values(container_memory_usage_bytes{namespace=~\".+\",container!=\"POD\"},namespace)"
   },
   {
    "name": "container",
    "query": "label_values(container_memory_usage_bytes{namespace=~\"$namespace\",container!=\"POD\"},container)"
   }
  ]
 },
 "panels": [
  { "title": "Total usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cluster memory usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id=\"/\"}) / sum (machine_memory_bytes{}) * 100"
    }
   ]
  },
  {
   "title": "Cluster CPU usage (1m avg)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\"}[1m])) / sum (machine_cpu_cores{}) * 100"
    }
   ]
  },
  {
   "title": "Cluster filesystem usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_fs_usage_bytes{}) / sum (container_fs_limit_bytes{id=\"/\"}) * 100"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 6 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{id=\"/\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 6 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    { "expr": "sum (machine_memory_bytes{})" }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\"}[1m]))"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "sum (machine_cpu_cores{})" }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 6 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_fs_usage_bytes{id=\"/\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 6 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_fs_limit_bytes{id=\"/\"})"
    }
   ]
  },
  {
   "title": "kubernetes-control-plane CPU idle",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "kubernetes-control-plane CPU idle",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "cpu_usage_idle{cpu=\"cpu-total\",host=~\".*kubernetes-master.*\"}",
       "legendFormat": "{{host}}"
      }
     ]
    }
   ]
  },
  {
   "title": "kubernetes-worker CPU idle",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "kubernetes-worker CPU idle",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "cpu_usage_idle{cpu=\"cpu-total\",host=~\".*kubernetes-worker.*\"}",
       "legendFormat": "{{host}}"
      }
     ]
    }
   ]
  },
  {
   "title": "API server",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "API request latency",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "sum(rate(apiserver_request_duration_seconds_sum{}[1m])) / sum(rate(apiserver_request_duration_seconds_count{}[1m]))",
       "legendFormat": "{{username}}"
      }
     ]
    },
    {
     "title": "API server hits by code",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(apiserver_request_total{}[1m])) by (code)",
       "legendFormat": "{{code}}"
      }
     ]
    },
    {
     "title": "Authenticated user requests",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(authenticated_user_requests{}[1m])",
       "legendFormat": "{{username}}"
      }
     ]
    },
    {
     "title": "API request latency by resource 95th percentile",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(apiserver_request_duration_seconds_bucket{}[5m])) by (le,resource) )",
       "legendFormat": "{{resource}}"
      }
     ]
    },
    {
     "title": "API request latency by request method 95th percentile",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(apiserver_request_duration_seconds_bucket{}[5m])) by (le,verb) )",
       "legendFormat": "{{verb}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Admission controller",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Admission requests (10min avg)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "rate(workqueue_adds_total{}[10m])",
       "legendFormat": "{{ name }}"
      }
     ]
    },
    {
     "title": "Admission controller queue latency (10min avg)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 32 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "rate(workqueue_queue_duration_seconds_sum{}[10m]) / rate(workqueue_queue_duration_seconds_count{}[10m])",
       "legendFormat": "{{ name }}"
      }
     ]
    },
    {
     "title": "Admission controller work (10min avg)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 39 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "rate(workqueue_work_duration_seconds_sum{}[10m]) / rate(workqueue_work_duration_seconds_count{}[10m])",
       "legendFormat": "{{ name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Etcd",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Etcd request latencies",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(etcd_request_duration_seconds_bucket[5m])) by (le))",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(etcd_request_duration_seconds_bucket[5m])) by (le))",
       "legendFormat": "p90"
      },
      {
       "expr": "histogram_quantile(0.5, sum(rate(etcd_request_duration_seconds_bucket[5m])) by (le))",
       "legendFormat": "p50"
      }
     ]
    }
   ]
  },
  {
   "title": "Pods CPU usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pods CPU usage (1m avg)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 48 },
     "yaxes": [
      { "format": "none", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum(rate (container_cpu_usage_seconds_total{image!=\"\",container=~\"$container\",namespace=~\"$namespace\"}[1m])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Containers CPU usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Container CPU usage (1m avg)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 49 },
     "yaxes": [
      { "format": "none", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum(rate (container_cpu_usage_seconds_total{image!=\"\",container!=\"POD\",container=~\"$container\",namespace=~\"$namespace\"}[1m])) without (cpu)",
       "legendFormat": "{{container}} (pod: {{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "System services CPU usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "System services CPU usage (1m avg)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 50 },
     "yaxes": [
      { "format": "none", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{id=~\".*systemd.*service$\"}[1m])) by (id)",
       "legendFormat": "{{id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "All processes CPU usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "All processes CPU usage (1m avg)",
     "type": "graph",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 51 },
     "yaxes": [
      { "format": "none", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{id!=\"/\"}[1m])) by (id)",
       "legendFormat": "{{id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Pods memory usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pods memory usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 52 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{image!=\"\",container=~\"$container\",namespace=~\"$namespace\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Containers memory usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Containers memory usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 53 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{image!=\"\",container!=\"POD\",container=~\"$container\",namespace=~\"$namespace\"}) by (container, pod)",
       "legendFormat": "{{container}} (pod: {{pod}})"
      }
     ]
    }
   ]
  },
  {
   "title": "System services memory usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "System services memory usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 54 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{id=~\".*systemd.*service$\"}) by (id)",
       "legendFormat": "{{id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "All processes memory usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "All processes memory usage",
     "type": "graph",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 55 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{id!=\"/\"}) by (id)",
       "legendFormat": "{{id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network I/O pressure",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_network_receive_bytes_total{}[1m]))",
       "legendFormat": "Received"
      },
      {
       "expr": "- sum (rate (container_network_transmit_bytes_total{}[1m]))",
       "legendFormat": "Sent"
      }
     ]
    }
   ]
  },
  {
   "title": "Pods network I/O",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pods network I/O (1m avg)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_network_receive_bytes_total{image!=\"\",pod=~\"$container.*\",namespace=~\"$namespace\"}[1m])) by (pod)",
       "legendFormat": "-> {{pod}}"
      },
      {
       "expr": "- sum (rate (container_network_transmit_bytes_total{image!=\"\",pod=~\"$container.*\",namespace=~\"$namespace\"}[1m])) by (pod)",
       "legendFormat": "<- {{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "All processes network I/O",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "All processes network I/O (1m avg)",
     "type": "graph",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_network_receive_bytes_total{id!=\"/\"}[1m])) by (id)",
       "legendFormat": "-> {{id}}"
      },
      {
       "expr": "- sum (rate (container_network_transmit_bytes_total{id!=\"/\"}[1m])) by (id)",
       "legendFormat": "<- {{id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Container Disk Utilisation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Bytes Used By Containers",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 59 },
     "yaxes": [
      { "format": "bytes", "label": "Bytes" }
     ],
     "targets": [
      {
       "expr": "sum by (container) (container_fs_usage_bytes{id!=\"/\"})",
       "legendFormat": "{{container}}"
      }
     ]
    },
    {
     "title": "Current Usage Breakdown By Container",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 59 },
     "yaxes": [
      { "format": "percent", "label": "Percent" }
     ],
     "targets": [
      {
       "expr": "sum by (container) (container_fs_usage_bytes{id!=\"/\"}) / on (environment) group_left(id) sum (container_fs_usage_bytes{id=\"/\"}) * 100",
       "legendFormat": "{{container}}"
      }
     ]
    },
    {
     "title": "Total Bytes Not Used By Containers",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 59 },
     "format": "bytes",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(container_fs_usage_bytes{id=\"/\"}) - sum(container_fs_usage_bytes{id!=\"/\"})"
      }
     ]
    }
   ]
  }
 ]
}